figure(10); clf;
axis off;

text(0.01, 0.5, ...
'H_m = (z_B - z_A) + (\Sigma_s f_s L_s/D_s + \Sigma_s k_s) Q^2/(2 g A_s^2) + (\Sigma_d f_d L_d/D_d + \Sigma_d k_d) Q^2/(2 g A_d^2)', ...
'Interpreter','tex', ...
'FontSize', 14);
